name: My First GitHub Workflow

on:
  push:
    branches: [ "main" ]

jobs:
  make-docker-image:
    runs-on: ubuntu-latest

    steps:
      - name: checkout to main
        uses: actions/chekout@v2 
        with: 
          ref: main
      
      - name: chekout to devops branch
        run: git chekcout devops

      - name: pull from main
        run: git pull origin main
      
      - name: set up docker
        uses: docker/setup-buildx-action@v2

      - name: login to docker
        uses: docker/login-action@v3 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/drag-and-drop-app:latest
