name: first

on:
    push:
        branches:
            - main

jobs: 
    build:
        runs-on:
            ubuntu-latest
        
        steps:
            - name: chekout repository main
              uses: actions/checkout@v4
              with:
                ref: main
            - name: list 1 all the branches 
              run: git branch --list 
            - name: git fetch branches
              run: git fetch
            - name: list 2 all the branches
              run: git branch --list 
            - name: checkout to dev
              run: git checkout dev

