name: first

on:
    push:
        branches:
            - main

jobs: 
    build:
        runs-on:
            ubuntu-latest
        
        steps:
            - name: chekout repository main
              uses: actions/checkout@v4
              with:
                ref: main
            - name: checkout to dev
              run: git checkout dev -- Dockerfile
            - name: setup docker
              uses: docker/setup-buildx-action@v3
            - name: build docker image
              run: docker build -t test:latest .  

